FROM nvidia/cuda:11.1-cudnn8-runtime-ubuntu20.04
ENV CMAKE_FILE=cmake-3.15.7-Linux-x86_64.sh \
    CONDA_FILE=Miniconda3-py38_4.10.3-Linux-x86_64.sh \
    PATH=/root/miniconda3/bin:/usr/local/cmake/bin:$PATH
ARG build=/home/wenet/runtime/server/x86/build
ADD kaldi /home/kaldi 
RUN rm /bin/sh && ln -s /bin/bash /bin/sh && \
    apt-get update && apt-get install --no-install-recommends -y git cmake wget build-essential lsof vim libmad0-dev sox libsox-dev gdb bzip2 unzip && \
    cd /root && wget https://repo.anaconda.com/miniconda/$CONDA_FILE && sed -i '59d' $CONDA_FILE && sed -i '59i BATCH=1' $CONDA_FILE && \
    sh $CONDA_FILE && > /root/$CONDA_FILE && rm -rf /root/$CONDA_FILE && \
    echo "export PATH=/root/miniconda3/bin:\$PATH" >> /root/.bashrc  && \
    wget https://cmake.org/files/v3.15/$CMAKE_FILE && mkdir -p /usr/local/cmake && \
    sh  $CMAKE_FILE --prefix=/usr/local/cmake --skip-license && > $CMAKE_FILE && rm -rf $CMAKE_FILE && \
    echo "export PATH=/usr/local/cmake/bin:\$PATH" >> /root/.bashrc && \
    git clone https://github.com/wenet-e2e/wenet.git /home/wenet && \
    cd /home/wenet && pip install -r requirements.txt && conda install pytorch=1.10.0 torchvision torchaudio=0.10.0 cudatoolkit=11.1 -c pytorch -c conda-forge && conda install -y ipython && \
    pip install flask && \
    mkdir $build && cd $build && cmake -DGRPC=ON .. && cmake --build . && \
    apt-get clean
RUN apt-get install --no-install-recommends -y  zlib1g-dev automake autoconf gfortran libtool subversion python2.7 gawk && \
    cd /home/kaldi/tools && ./install_liblbfgs.sh && ./install_srilm.sh name organization e@mail.com
WORKDIR  /home/
#CMD ["/bin/bash"]
